# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'real_akskubernetes'
    azureResourceGroup: 'DevOps'
    kubernetesCluster: 'titemiaks'
    namespace: 'default'
    command: 'apply'
    arguments: '-f $(System.DefaultWorkinDirectory)/deployment2.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
